#服务启动端口号
server:
  port: 8003
 
spring:
  application:
   name: provider8000
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance: 
    instance-id: provider-8003  #更改服务客户端显示名