#服务启动端口号
server:
  port: 8002
 
spring:
  application:
    name: provider8000
    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance: 
    instance-id: provider-8002  #更改服务客户端显示名